name: Testar código

on: [push]

jobs:
  testar-codigo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Esta ação faz o checkout do repositório
    
    - name: Check current directory
      run: |
        pwd  # Exibe o diretório atual
        ls   # Lista o conteúdo do diretório
        
    - name: Run Python script
      run: python main.py  # Substitua 'main.py' pelo nome do seu arquivo Python